name: marketing-analysis
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyter
  - jupyter_contrib_nbextensions
  - pandas
  - xlrd
  - scipy
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - xgboost
  - statsmodels
  - keras
  - click
  - requests
  - black
  - pytest
  - pytest-mock
  - requests-mock
  - pip
  - pip:
    - -e ./
    - yellowbricks
    - -e git+https://github.com/dilshod/xlsx2csv#egg=xlsx2csv
